apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filemanager-route
  namespace: {{ .Release.Namespace }}
  labels:
    managed-by: orchestration
    user: "{{ .Values.user.username }}"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.filemanager.host }}`) && PathPrefix(`/{{ .Values.user.username }}`)
      kind: Rule
      priority: 50
      middlewares:
        - name: "{{ .Values.orchestrationNamespace }}-{{ .Values.authMiddleware }}@kubernetescrd"
        - name: "{{ .Values.orchestrationNamespace }}-{{ .Values.stripMiddleware | default "strip-prefix" }}@kubernetescrd"
      services:
        - name: "{{ include "php-multisite.fullname" . }}"
          port: 80
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: "{{ .Values.tlsSecret }}"